Giftbox/Controllers/PredictController.cs
using Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Giftbox.Controllers
{
    public class PredictController : Controller
    {
        // GET: Predict
        public ActionResult Index()
        {
            //
            int IDUser = HttpContext.Session["IDUser"] == null ? 0 : (int)HttpContext.Session["IDUser"];
            if (IDUser <= 0)
            {
                return RedirectToAction("Index", "Login");
            }
            GiftboxEntities db = new GiftboxEntities();
            var DBUser = db.User.Where(m => m.ID != IDUser && m.Status == 1).AsQueryable();
            List<UserModel> UserList = new List<UserModel>();
            UserList = DBUser.ToList().Select(EntityToModel).ToList();

            ViewBag.ListUser = db.User.Where(m => m.Status == 1).ToList().Select(EntityToModel).ToList();
            return PartialView(UserList);
        }
        private UserModel EntityToModel(User Value)
        {
            return new UserModel()
            {
                ID = Value.ID,
                Name = Value.Name,
                Username = Value.Username,
                Password = Value.Password,
                Status = Value.Status
            };
        }
        [HttpPost]
        public ActionResult Selection(SelectionModel Value)
        {
            using (GiftboxEntities db = new GiftboxEntities())
            {
                int IDUser = HttpContext.Session["IDUser"] == null ? 0 : (int)HttpContext.Session["IDUser"];
                if (IDUser <= 0)
                {
                    return RedirectToAction("Index", "Login");
                }

                for (int i = 0; i <= Value.GiverID.Count - 1; i++)
                {

                    db.Selection.Add(new Selection
                    {
                        GiverID = Value.GiverID[i],
                        ReceiverID = Value.ReceiverID[i],
                        UserID = IDUser,
                        Status = false,
                    });
                }
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Results()
        {
            SelectionShow UserList = new SelectionShow();
            using (GiftboxEntities db = new GiftboxEntities())
            {
                int IDUser = HttpContext.Session["IDUser"] == null ? 0 : (int)HttpContext.Session["IDUser"];
                if (IDUser <= 0)
                {
                    return RedirectToAction("Index", "Login");
                }
                //income
                //check Userid How true count it : Answer Inner join selection
                //expenses
                //check Userid in Answer DB : check in Selection true count it



               

                var ansFilter_f = (from ans in db.Answer
                                   join sel in db.Selection
                                   on ans.UserID equals sel.GiverID
                                   where ans.UserID == sel.GiverID && ans.ReceiverID == sel.ReceiverID
                                   orderby ans.UserID ascending
                                   select new { GiverID = ans.UserID, ReceiverID = sel.ReceiverID, UserID = sel.UserID });

                var DBansFilter = ansFilter_f.Where(m => m.UserID == IDUser).ToList();

                //var test = DBansFilter.GroupBy(s => s.UserID).Select(x => new
                //{
                //    Userid = x.Key,
                //    giveId = x.Select(s=> new { Ans =s.GiverID }).ToList(),
                //    receiverID = x.Select(s => new { Ans = s.ReceiverID }).ToList()
                //}).ToList();

                //var exp = DBansFilter.GroupBy(s => s.GiverID).Select(x => new
                //{
                //    Userid = x.Key,
                //    giveId = x.Select(s => new { Ans = s.UserID }).ToList(),
                //    receiverID = x.Select(s => new { Ans = s.ReceiverID }).ToList()
                //}).ToList();

                var UserLists = db.Selection.Where(m => m.UserID == IDUser).AsQueryable().ToList();

                UserList.ID = UserLists.FirstOrDefault().ID;
                UserList.Status = new List<bool>();
                UserList.UserID = UserLists.FirstOrDefault().UserID;
                UserList.GiverID = new List<int>();
                UserList.ReceiverID = new List<int>();
                UserList.GiverName = new List<string>();
                UserList.ReceiverName = new List<string>();


                foreach (var item in UserLists)
                {
                    string gatGiverName = db.User.Where(w => w.ID == item.GiverID).FirstOrDefault().Name;
                    UserList.GiverName.Add(gatGiverName);
                    string gatReceiverName = db.User.Where(w => w.ID == item.ReceiverID).FirstOrDefault().Name;
                    UserList.ReceiverName.Add(gatReceiverName);
                    if (DBansFilter.Any(w => w.GiverID == item.GiverID) && DBansFilter.Any(w => w.ReceiverID == item.ReceiverID))
                    {
                        UserList.Status.Add(true);
                        var FindID = db.Selection.FirstOrDefault(w => w.ID == item.ID && w.UserID == item.UserID);
                        if (FindID != null)
                        {
                            FindID.Status = true;
                        }
                        try
                        {
                            db.SaveChanges();
                        }
                        catch (Exception ex)
                        {

                        }
                    }
                    else
                    {
                        UserList.Status.Add(item.Status);
                    }
                }

                int money = db.Selection.Where(w => w.Status == true && w.UserID == IDUser).Count();
                ViewBag.money = money;
                ViewBag.total = money * 20;
            }
            return View(UserList);
        }

    }
}

Giftbox/Controllers/ShowController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Giftbox.Controllers
{
    public class ShowController : Controller
    {
        // GET: Show
        public ActionResult Index()
        {
            GiftboxEntities db = new GiftboxEntities();
            int IDUser = HttpContext.Session["IDUser"] == null ? 0 : (int)HttpContext.Session["IDUser"];
            if (IDUser <= 0)
            {
                return RedirectToAction("Index", "Login");
            }
            var DataList = db.User.ToList();

            var DBSelection = db.Selection.AsQueryable();

            var ansFilter_f = (from ans in db.Answer
                               join sel in db.Selection
                               on ans.UserID equals sel.GiverID
                               where ans.UserID == sel.GiverID && ans.ReceiverID == sel.ReceiverID
                               orderby ans.UserID ascending
                               select new { GiverID = ans.UserID, ReceiverID = sel.ReceiverID, UserID = sel.UserID });

            var DBansFilter = ansFilter_f.ToList();

            var income = DBansFilter.GroupBy(s => s.UserID).Select(x => new 
            {
                UserID = x.Key,
                Name = db.User.Where(m => m.ID == x.Key).FirstOrDefault().Name,
                Correct = x.Select(s => new { GiverID = s.GiverID }).Count() * 20,
                exp = 0
            }).ToList();

            ViewBag.DataList = income;

            var exp = DBansFilter.GroupBy(s => s.GiverID).Select(x => new 
            {
                UserID = x.Key,
                Name = db.User.Where(m => m.ID == x.Key).FirstOrDefault().Name,
                Correct = 0,
                exp = x.Select(s => new { ReceiverID = s.ReceiverID }).Count() * 20,
            }).ToList();
            ViewBag.DataList = exp;

            //var InandExp = income.GroupJoin(exp, inc => inc.UserID, expgj => expgj.UserID, (inc, expgj) => new ShowModel
            //{
            //    UserID = inc.UserID,
            //    Name = inc.Name,
            //    income = inc.Correct,
            //    exp = expgj.Select(s => s.exp).FirstOrDefault(),
            //    total = inc.Correct - expgj.Select(s => s.exp).FirstOrDefault()
            //}).ToList();
            var InandExp = income.Union(exp).GroupBy(g => g.UserID).Select(s => new ShowModel
            {
                UserID = s.Key,
                Name = s.Select(se => se.Name).FirstOrDefault(),
                income = s.Sum(su => su.Correct),
                exp = s.Sum(su => su.exp),
                total = s.Sum(su => su.Correct) - s.Sum(su => su.exp)
            }).ToList();

            return View(InandExp);

        }
    }
}

Giftbox/Views/Show/Index.cshtml
@model List<Models.ShowModel>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show</title>
    <style>
        html, body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 16px;
            color: #000000;
            background-color: #EBE5DC;
            margin: 0px;
            padding: 0px;
        }

        h1, h2, h3, h4, h5, h6 {
            font-family: Arial, Helvetica, sans-serif;
            margin: 10px 0px 10px 0px;
            text-align: center;
        }

        .row {
            display: flex;
            padding: 0px;
            margin: 0px;
        }

        .col-1 {
            width: 8.33%;
        }

        .col-2 {
            width: 16.66%;
        }

        .col-3 {
            width: 25%;
        }

        .col-4 {
            width: 33.33%;
        }

        .col-5 {
            width: 41.66%;
        }

        .col-6 {
            width: 50%;
        }

        .col-7 {
            width: 58.33%;
        }

        .col-8 {
            width: 66.66%;
        }

        .col-9 {
            width: 75%;
        }

        .col-10 {
            width: 83.33%;
        }

        .col-11 {
            width: 91.66%;
        }

        .col-12 {
            width: 100%;
        }

        .BGGiftbox {
            display: block;
            margin: auto;
            box-shadow: 3px 3px 25px 3px rgba(50, 50, 50, .2);
        }

        .login_div {
            display: table;
            float: right;
            margin: 100px 0;
            width: 400px;
        }

        table {
            width: 100%;
            margin-bottom: 10px;
        }

        tr, td {
            width: 25%;
        }

        td {
            text-align: center;
        }

        p {
            padding: 0px;
            margin: 5px 0;
        }

        .BTNSubmit {
            cursor: pointer;
            width: 50%;
            color: white;
            padding: 10px;
            background-color: #333333;
            border: none;
            text-decoration-line: none;
            font-size: 16px;
            font-family: 'Montserrat', sans-serif;
            float:right;
        }

            .BTNSubmit:hover {
                background-color: #333344;
            }

        .BTNLogout {
            cursor: pointer;
            width: 50%;
            color: #333333;
            padding: 10px;
            border: none;
            background-color: transparent;
            text-decoration-line: none;
            font-size: 16px;
            font-family: 'Montserrat', sans-serif;
            transition:.3s;
        }

            .BTNLogout:hover {
                color: #CB5454;
            }


        input[type="text"], input[type="password"] {
            padding: 12px 7px 12px 20px;
            width: 90%;
            font-size: 14px;
            border: none;
            background-color: #FAF6F5;
        }

        a {
            text-decoration: none;
            color: #333333;
        }

            a:hover {
                color: #A74444;
            }

        .div-425, .div-768 {
            display: none;
        }


        /*<!===================================================================!>*/
        .card {
            width: 270px;
            font-family: arial;
            margin: 10px 13px;
            display: inline-block;
        }

        .title {
            font-size: 30px;
            font-weight: bold;
            text-align: center;
        }

        .list {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            background-color: #FAF4F6;
            border-radius: 15px;
            color: #333333;
            padding: 25px 10px;
        }

        a {
            text-decoration: none;
            font-size: 22px;
            color: black;
        }

        .head {
            font-size: 24px;
        }

        /*<!===================================================================!>*/

        @@media screen and (max-width: 1440px) {
        }

        @@media screen and (max-width: 1024px) {
            .card {
                width: 300px;
                font-family: arial;
                margin: 10px 19px;
                display: inline-block;
            }
        }

        @@media screen and (max-width: 768px) {
            .div-1024, .div-425 {
                display: none;
            }

            .div-768 {
                display: table;
                width: 100%;
            }

            .BGGiftbox {
                width: 80%;
                display: block;
                margin: auto;
                box-shadow: 3px 3px 25px 3px rgba(50, 50, 50, .2);
            }

            .login_div {
                display: table;
                width: 80%;
                margin: 20% 0px;
            }

            .card {
                width: 300px;
                font-family: arial;
                margin: 10px auto;
                display: block;
            }
        }

        @@media screen and (max-width: 425px) {
            .div-1024, .div-768 {
                display: none;
            }

            .div-425 {
                display: table;
                width: 100%;
            }

            .login_div {
                display: table;
                width: 80%;
            }

            .card {
                width: 100%;
                font-family: arial;
                margin: 10px auto;
                display: block;
            }
            .BTNSubmit {
            cursor: pointer;
            width: 100%;
            color: white;
            padding: 10px;
            background-color: #333333;
            border: none;
            text-decoration-line: none;
            font-size: 16px;
            font-family: 'Montserrat', sans-serif;
            float:right;
        }

            .BTNSubmit:hover {
                background-color: #333344;
            }

        .BTNLogout {
            cursor: pointer;
            width: 100%;
            color: #333333;
            padding: 10px;
            border: none;
            background-color: transparent;
            text-decoration-line: none;
            font-size: 16px;
            font-family: 'Montserrat', sans-serif;
            transition:.3s;
        }

            .BTNLogout:hover {
                color: #CB5454;
            }
        }
    </style>

</head>
<body>
    
    <div class="div-1024">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <h1>Result</h1>
                <div class="row">
                    <div class="col-6"><a href="@Url.Action("Results", "Predict")"><button class="BTNSubmit">Detail</button></a></div>
                    <div class="col-6"><a href="@Url.Action("Logout", "Login")"><button class="BTNLogout">Logout</button></a></div>
                </div>
                
                <p></p>
                @foreach (Models.ShowModel item in Model)
                {
                    <div class="card">
                        <p class="title">
                            @item.Name
                        </p>
                        <table class="list">
                            <tr>
                                <td style="border-right:1px solid #ccc">
                                    <p class="head"> @item.income฿</p>
                                    Income
                                </td>
                                <td style="border-right:1px solid #ccc">
                                    <p class="head">@item.exp฿</p>
                                    Expenses
                                </td>
                                <td>
                                    @if (item.total >= 0)
                                    {
                                        <p class="head">@item.total฿</p>
                                    }
                                    else
                                    {
                                        <p class="head" style="color:red;">@item.total฿</p>
                                    }
                                    Total
                                </td>
                            </tr>
                        </table>
                       
                    </div>
                }
                
            </div>
            <div class="col-2"></div>
        </div>
    </div>
   
    <div class="div-768">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <h1>Result</h1>
                <div class="row">
                    <div class="col-6"><a href="@Url.Action("Results", "Predict")"><button class="BTNSubmit">Detail</button></a></div>
                    <div class="col-6"><a href="@Url.Action("Logout", "Login")"><button class="BTNLogout">Logout</button></a></div>
                </div>

                <p></p>
                @foreach (Models.ShowModel item in Model)
                {
                    <div class="card">
                        <p class="title">
                            @item.Name
                        </p>
                        <table class="list">
                            <tr>
                                <td style="border-right:1px solid #ccc">
                                    <p class="head"> @item.income฿</p>
                                    Income
                                </td>
                                <td style="border-right:1px solid #ccc">
                                    <p class="head">@item.exp฿</p>
                                    Expenses
                                </td>
                                <td>
                                    @if (item.total >= 0)
                                    {
                                        <p class="head">@item.total฿</p>
                                    }
                                    else
                                    {
                                        <p class="head" style="color:red;">@item.total฿</p>
                                    }
                                    Total
                                </td>
                            </tr>
                        </table>

                    </div>
                }

            </div>
            <div class="col-2"></div>
        </div>
    </div>

    <div class="div-425">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <h1>Result</h1>
                <div class="row">
                    <div class="col-6"><a href="@Url.Action("Results", "Predict")"><button class="BTNSubmit">Detail</button></a></div>
                    <div class="col-6"><a href="@Url.Action("Logout", "Login")"><button class="BTNLogout">Logout</button></a></div>
                </div>

                <p></p>
                @foreach (Models.ShowModel item in Model)
                {
                    <div class="card">
                        <p class="title">
                            @item.Name
                        </p>
                        <table class="list">
                            <tr>
                                <td style="border-right:1px solid #ccc">
                                    <p class="head"> @item.income฿</p>
                                    Income
                                </td>
                                <td style="border-right:1px solid #ccc">
                                    <p class="head">@item.exp฿</p>
                                    Expenses
                                </td>
                                <td>
                                    @if (item.total >= 0)
                                    {
                                        <p class="head">@item.total฿</p>
                                    }
                                    else
                                    {
                                        <p class="head" style="color:red;">@item.total฿</p>
                                    }
                                    Total
                                </td>
                            </tr>
                        </table>

                    </div>
                }

            </div>
            <div class="col-2"></div>
        </div>
    </div>
</body>
</html>