Giftbox/Controllers/RegisterController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Giftbox.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(UserModel item)
        {

            using (GiftboxEntities db = new GiftboxEntities())
            {
                if (!String.IsNullOrEmpty(item.Username) && !String.IsNullOrEmpty(item.Password))
                {
                    
                    var userDetail = db.User.Where(m => m.Username == item.Username && m.Password == item.Password).FirstOrDefault();

                    if (userDetail != null)
                    {
                        if (userDetail.Status > 0)
                        {
                            item.LoginErrorMsg = "Have account";
                            return View("Index", item);
                        }
                        else
                        {
                            userDetail.Status = 1;
                        }

                    }
                    else
                    {
                        db.User.Add(new User
                        {
                            ID = db.User.Count() + 1,
                            Username = item.Username,
                            Password = item.Password,
                            Name = item.Name,
                            Status = 1
                        });

                    }
                    try
                    {
                        db.SaveChanges();
                        Session["IDUser"] = item.ID;
                        Session["Username"] = item.Username;
                        Session["Name"] = item.Name;
                        return RedirectToAction("Index", "Home");
                    }
                    catch (Exception ex)
                    {
                        item.LoginErrorMsg = ex.InnerException.ToString();
                        return View("Index", item);
                    }
                }
                else
                {
                    item.LoginErrorMsg = "Invaild UserName or Password";
                    return View("Index", item);
                }
                
            return RedirectToAction("Index", "Home");
        }
    }
}
}

Giftbox/Views/Register/Index.cshtml
@model Models.UserModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>

    <style>
        html, body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 16px;
            color: #000000;
            background-color: #EBE5DC;
            margin: 0px;
            padding: 0px;
        }

        h1, h2, h3, h4, h5, h6 {
            font-family: Arial, Helvetica, sans-serif;
            margin: 10px 0px 10px 0px;
            text-align: center;
        }

        .row {
            display: flex;
            padding: 0px;
            margin: 0px;
        }

        .col-1 {
            width: 8.33%;
        }

        .col-2 {
            width: 16.66%;
        }

        .col-3 {
            width: 25%;
        }

        .col-4 {
            width: 33.33%;
        }

        .col-5 {
            width: 41.66%;
        }

        .col-6 {
            width: 50%;
        }

        .col-7 {
            width: 58.33%;
        }

        .col-8 {
            width: 66.66%;
        }

        .col-9 {
            width: 75%;
        }

        .col-10 {
            width: 83.33%;
        }

        .col-11 {
            width: 91.66%;
        }

        .col-12 {
            width: 100%;
        }

        .BGGiftbox {
            display: block;
            margin: auto;
            box-shadow: 3px 3px 25px 3px rgba(50, 50, 50, .2);
        }

        .login_div {
            display: table;
            float:right;
            margin: 100px 0;
            width: 400px;
        }

        table {
            width: 100%;
        }

        td {
            padding: 5px;
        }

        .BTNSubmit {
            cursor: pointer;
            width: 100%;
            color: white;
            padding: 10px;
            background-color: #333333;
            border: none;
            text-decoration-line: none;
            font-size: 16px;
            font-family: 'Montserrat', sans-serif;
        }

            .BTNSubmit:hover {
                background-color: #333344;
            }


        input[type="text"], input[type="password"] {
            padding: 12px 7px 12px 20px;
            width: 90%;
            font-size: 14px;
            border: none;
            background-color: #FAF6F5;
        }

        a {
            text-decoration: none;
            color: #666666;
        }

            a:hover {
                color: #CB5454;
            }

        .div-425, .div-768 {
            display: none;
        }

        @@media screen and (max-width: 1440px) {
        }

        @@media screen and (max-width: 1024px) {
        }

        @@media screen and (max-width: 768px) {
            .div-1024, .div-425 {
                display: none;
            }

            .div-768 {
                display: table;
                width: 100%;
            }

            .BGGiftbox {
                width: 80%;
                display: block;
                margin: auto;
                box-shadow: 3px 3px 25px 3px rgba(50, 50, 50, .2);
            }

            .login_div {
                display: table;
                width: 80%;
                margin: 20% auto;
            }
        }

        @@media screen and (max-width: 425px) {
            .div-1024, .div-768 {
                display: none;
            }

            .div-425 {
                display: table;
                width: 100%;
            }

            .login_div {
                display: table;
                float:none;
                width: 80%;
                margin: 20% auto;
            }

            td {
                padding: 5px 0;
            }
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("Index", "Register", FormMethod.Post, new { id = "Register", enctype = "multipart/form-data" }))
    {
        <div class="div-1024">
            <div class="row">
                <div class="col-6">
                    <div class="login_div">
                        <h1>Sign Up</h1>
                        <table>
                            <tr>
                                <td>Name</td>
                                <td><input class="input" name="Name" type="text" placeholder="Name" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Username)</td>
                            </tr>
                            <tr>
                                <td>Username</td>
                                <td><input class="input" name="Username" type="text" placeholder="Username" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Username)</td>
                            </tr>
                            <tr>
                                <td>Password</td>
                                <td><input class="input" name="Password" type="password" placeholder="Password" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Password)</td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.DisplayFor(model => model.LoginErrorMsg)</td>
                            </tr>
                            <tr>
                                <td colspan="2"><input type="submit" value="Register" class="BTNSubmit" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center">
                                    <p>
                                        I have an account.
                                        <a href="@Url.Action("Index", "Login")">Sign In</a>
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-6">
                    <img src="~/Images/15-02.png" class="BGGiftbox" />
                </div>
            </div>
        </div>
    }
    @using (Html.BeginForm("Index", "Register", FormMethod.Post, new { id = "Register", enctype = "multipart/form-data" }))
    {
        <div class="div-768">
            <div class="row">
                <div class="col-6">
                    <div class="login_div">
                        <h1>Sign Up</h1>
                        <table>
                            <tr>
                                <td>Name</td>
                            </tr>
                            <tr>
                                <td><input class="input" name="Name" type="text" placeholder="Name" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Username)</td>
                            </tr>
                            <tr>
                                <td>Username</td>
                            </tr>
                            <tr>
                                <td><input class="input" name="Username" type="text" placeholder="Username" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Username)</td>
                            </tr>
                            <tr>
                                <td>Password</td>
                            </tr>
                            <tr>
                                <td><input class="input" name="Password" type="password" placeholder="Password" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Password)</td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.DisplayFor(model => model.LoginErrorMsg)</td>
                            </tr>
                            <tr>
                                <td colspan="2"><input type="submit" value="Register" class="BTNSubmit" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center">
                                    <p>
                                        I have an account.
                                        <a href="@Url.Action("Index", "Login")">Sign In</a>
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-6">
                    <img src="~/Images/15-02.png" class="BGGiftbox" />
                </div>
            </div>
        </div>
    }
    @using (Html.BeginForm("Index", "Register", FormMethod.Post, new { id = "Register", enctype = "multipart/form-data" }))
    {
        <div class="div-425">
            <div class="row">
                <div class="col-12">
                    <div class="login_div">
                        <h1>Sign Up</h1>
                        <table>
                            <tr>
                                <td>Name</td>
                            </tr>
                            <tr>
                                <td><input class="input" name="Name" type="text" placeholder="Name" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Username)</td>
                            </tr>
                            <tr>
                                <td>Username</td>
                            </tr>
                            <tr>
                                <td><input class="input" name="Username" type="text" placeholder="Username" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Username)</td>
                            </tr>
                            <tr>
                                <td>Password</td>
                            </tr>
                            <tr>
                                <td><input class="input" name="Password" type="password" placeholder="Password" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.ValidationMessageFor(model => model.Password)</td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center" style="color:#CB5454">@Html.DisplayFor(model => model.LoginErrorMsg)</td>
                            </tr>
                            <tr>
                                <td colspan="2"><input type="submit" value="Register" class="BTNSubmit" /></td>
                            </tr>
                            <tr>
                                <td colspan="2" align="center">
                                    <p>
                                        I have an account.
                                        <a href="@Url.Action("Index", "Login")">Sign In</a>
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    }
    <!--===============================================================================================-->
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <!--===============================================================================================-->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <!--===============================================================================================-->
    <script src="vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
</body>
</html>